version: '3'

services:
  zookeeper:
    image: zookeeper # Mac M1 Friendly
    ports:
      - "2181:2181"
    
  
  # This has three listeners you can experiment with. 
  # LISTENER_INTERNAL for internal traffic on the Docker network
  # LISTENER_DOCKERHOST for traffic from the Docker-host machine (`localhost`)
  # LISTENER_HOSTNAME for traffic from outside, reaching the Docker host on the DNS name `give-me-kafka`
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "29094:29094"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_DOCKERHOST://kafka:9092,LISTENER_HOSTNAME://kafka:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_DOCKERHOST://localhost:9092,LISTENER_HOSTNAME://give-me-kafka:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_DOCKERHOST:PLAINTEXT,LISTENER_HOSTNAME:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 10000
      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'false'
    depends_on:
      - zookeeper

  schema-registry:
    image: eugenetea/schema-registry-arm64:latest # Mac M1 Friendly 
    hostname: schema-registry
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
    depends_on:
      - zookeeper
      - kafka