version: '3'

services:
  zookeeper:
    image: zookeeper:3.7.0 # Mac M1 Friendly
    ports:
      - "2181:2181"
  
  # This has three listeners you can experiment with. 
  # LISTENER_INTERNAL for internal traffic on the Docker network
  # LISTENER_DOCKERHOST for traffic from the Docker-host machine (`localhost`)
  # LISTENER_HOSTNAME for traffic from outside, reaching the Docker host on the DNS name `give-me-kafka`
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
      - "29094:29094"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_DOCKERHOST://kafka:9092,LISTENER_HOSTNAME://kafka:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_DOCKERHOST://localhost:9092,LISTENER_HOSTNAME://give-me-kafka:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_DOCKERHOST:PLAINTEXT,LISTENER_HOSTNAME:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 10000
      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'false'
    depends_on:
      - zookeeper

  schema-registry:
    image: eugenetea/schema-registry-arm64:latest # Mac M1 Friendly 
    hostname: schema-registry
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
    depends_on:
      - kafka
      
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.23.1
    hostname: ksqldb-server
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:29092 
      KSQL_LISTENERS: http://0.0.0.0:8088/
      KSQL_KSQL_SERVICE_ID: ksql_service_
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_AUTO_OFFSET_RESET: earliest
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
  
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.19.0
    depends_on:
      - kafka
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true