global using System;
global using System.Threading.Tasks;
global using Confluent.Kafka;
global using Grpc.Core;
global using KitchenOrders;
global using Microsoft.Extensions.Logging;
global using Common.Kafka;
global using KitchenOrders.Messages;
global using Common.Models;