// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// avrogen -s Orders.3.avsc .
// ------------------------------------------------------------------------------
namespace KitchenOrders.Messages
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Represents a successfully created kitchen order.
	/// </summary>
	public partial class Order : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Order\",\"doc\":\"Represents a successfully created kitchen " +
				"order.\",\"namespace\":\"KitchenOrders.Messages\",\"fields\":[{\"name\":\"orderId\",\"type\":" +
				"\"string\"},{\"name\":\"orderCreated\",\"type\":\"long\"}]}");
		private string _orderId;
		private long _orderCreated;
		public virtual Schema Schema
		{
			get
			{
				return Order._SCHEMA;
			}
		}
		public string orderId
		{
			get
			{
				return this._orderId;
			}
			set
			{
				this._orderId = value;
			}
		}
		public long orderCreated
		{
			get
			{
				return this._orderCreated;
			}
			set
			{
				this._orderCreated = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.orderId;
			case 1: return this.orderCreated;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.orderId = (System.String)fieldValue; break;
			case 1: this.orderCreated = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
