// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KitchenOrders.Messages
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Represents a successfully created kitchen order.
	/// </summary>
	public partial class Order : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Order"",""doc"":""Represents a successfully created kitchen order."",""namespace"":""KitchenOrders.Messages"",""fields"":[{""name"":""orderId"",""type"":""string""},{""name"":""orderCreated"",""type"":""long""},{""name"":""productId"",""type"":""string""},{""name"":""quantity"",""type"":""int""}]}");
		private string _orderId;
		private long _orderCreated;
		private string _productId;
		private int _quantity;
		public virtual Schema Schema
		{
			get
			{
				return Order._SCHEMA;
			}
		}
		public string orderId
		{
			get
			{
				return this._orderId;
			}
			set
			{
				this._orderId = value;
			}
		}
		public long orderCreated
		{
			get
			{
				return this._orderCreated;
			}
			set
			{
				this._orderCreated = value;
			}
		}
		public string productId
		{
			get
			{
				return this._productId;
			}
			set
			{
				this._productId = value;
			}
		}
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.orderId;
			case 1: return this.orderCreated;
			case 2: return this.productId;
			case 3: return this.quantity;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.orderId = (System.String)fieldValue; break;
			case 1: this.orderCreated = (System.Int64)fieldValue; break;
			case 2: this.productId = (System.String)fieldValue; break;
			case 3: this.quantity = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
